export interface DetailedReportRow {
  id: string;
  date: string;
  parlorCode: string;
  parlorName: string;
  parlorType: 'Mall' | 'Standalone' | 'Event' | 'Kiosk';
  routeCode: string;
  agentCode: string;
  agentName: string;
  supervisorCode: string;
  supervisorName: string;
  cashAmount: number;
  couponAmount: number;
  ccAmount: number;
  total: number;
  status: 'submitted' | 'acknowledged';
}

export interface SummaryReportRow {
  id: string;
  agentCode: string;
  agentName: string;
  routeCode: string;
  supervisorCode: string;
  supervisorName: string;
  parlorCount: number;
  totalCash: number;
  totalCoupon: number;
  totalCC: number;
  grandTotal: number;
  acknowledgedCount: number;
  pendingCount: number;
}

export const DETAILED_REPORT_DATA: DetailedReportRow[] = [
  {
    id: 'det-001',
    date: '08/05/2026',
    parlorCode: 'PRL-001',
    parlorName: 'Nexus Mall — Koramangala',
    parlorType: 'Mall',
    routeCode: 'RT-04',
    agentCode: 'AGT-042',
    agentName: 'Rajan Kumar',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    cashAmount: 12450,
    couponAmount: 3200,
    ccAmount: 18900,
    total: 34550,
    status: 'acknowledged',
  },
  {
    id: 'det-002',
    date: '08/05/2026',
    parlorCode: 'PRL-007',
    parlorName: 'Forum Value Mall',
    parlorType: 'Mall',
    routeCode: 'RT-04',
    agentCode: 'AGT-042',
    agentName: 'Rajan Kumar',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    cashAmount: 8750,
    couponAmount: 1500,
    ccAmount: 22100,
    total: 32350,
    status: 'submitted',
  },
  {
    id: 'det-003',
    date: '08/05/2026',
    parlorCode: 'PRL-062',
    parlorName: 'Electronic City Phase 1',
    parlorType: 'Standalone',
    routeCode: 'RT-04',
    agentCode: 'AGT-038',
    agentName: 'Priya Nair',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    cashAmount: 11200,
    couponAmount: 2800,
    ccAmount: 15600,
    total: 29600,
    status: 'submitted',
  },
  {
    id: 'det-004',
    date: '08/05/2026',
    parlorCode: 'PRL-074',
    parlorName: 'Sarjapur Road Outlet',
    parlorType: 'Standalone',
    routeCode: 'RT-05',
    agentCode: 'AGT-051',
    agentName: 'Suresh Babu',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    cashAmount: 5400,
    couponAmount: 600,
    ccAmount: 8900,
    total: 14900,
    status: 'submitted',
  },
  {
    id: 'det-005',
    date: '08/05/2026',
    parlorCode: 'PRL-083',
    parlorName: 'Bannerghatta Road Mall',
    parlorType: 'Mall',
    routeCode: 'RT-04',
    agentCode: 'AGT-029',
    agentName: 'Anita Desai',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    cashAmount: 14300,
    couponAmount: 4100,
    ccAmount: 27800,
    total: 46200,
    status: 'submitted',
  },
  {
    id: 'det-006',
    date: '07/05/2026',
    parlorCode: 'PRL-001',
    parlorName: 'Nexus Mall — Koramangala',
    parlorType: 'Mall',
    routeCode: 'RT-04',
    agentCode: 'AGT-042',
    agentName: 'Rajan Kumar',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    cashAmount: 10200,
    couponAmount: 2700,
    ccAmount: 16400,
    total: 29300,
    status: 'acknowledged',
  },
  {
    id: 'det-007',
    date: '07/05/2026',
    parlorCode: 'PRL-019',
    parlorName: 'Jayanagar 4th Block',
    parlorType: 'Standalone',
    routeCode: 'RT-04',
    agentCode: 'AGT-042',
    agentName: 'Rajan Kumar',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    cashAmount: 4800,
    couponAmount: 900,
    ccAmount: 7200,
    total: 12900,
    status: 'acknowledged',
  },
  {
    id: 'det-008',
    date: '07/05/2026',
    parlorCode: 'PRL-031',
    parlorName: 'Whitefield ITPL Gate',
    parlorType: 'Event',
    routeCode: 'RT-04',
    agentCode: 'AGT-038',
    agentName: 'Priya Nair',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    cashAmount: 18600,
    couponAmount: 5200,
    ccAmount: 31400,
    total: 55200,
    status: 'acknowledged',
  },
  {
    id: 'det-009',
    date: '07/05/2026',
    parlorCode: 'PRL-044',
    parlorName: 'Koramangala 5th Block Kiosk',
    parlorType: 'Kiosk',
    routeCode: 'RT-05',
    agentCode: 'AGT-051',
    agentName: 'Suresh Babu',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    cashAmount: 3200,
    couponAmount: 400,
    ccAmount: 5600,
    total: 9200,
    status: 'acknowledged',
  },
  {
    id: 'det-010',
    date: '06/05/2026',
    parlorCode: 'PRL-057',
    parlorName: 'Marathahalli Bridge',
    parlorType: 'Kiosk',
    routeCode: 'RT-06',
    agentCode: 'AGT-063',
    agentName: 'Vikram Singh',
    supervisorCode: 'SUP-017',
    supervisorName: 'Deepa Rao',
    cashAmount: 2900,
    couponAmount: 350,
    ccAmount: 4800,
    total: 8050,
    status: 'acknowledged',
  },
  {
    id: 'det-011',
    date: '06/05/2026',
    parlorCode: 'PRL-068',
    parlorName: 'MG Road Premium',
    parlorType: 'Standalone',
    routeCode: 'RT-06',
    agentCode: 'AGT-063',
    agentName: 'Vikram Singh',
    supervisorCode: 'SUP-017',
    supervisorName: 'Deepa Rao',
    cashAmount: 9800,
    couponAmount: 2100,
    ccAmount: 14300,
    total: 26200,
    status: 'acknowledged',
  },
  {
    id: 'det-012',
    date: '06/05/2026',
    parlorCode: 'PRL-089',
    parlorName: 'Hebbal Lake View',
    parlorType: 'Standalone',
    routeCode: 'RT-07',
    agentCode: 'AGT-071',
    agentName: 'Kavitha Menon',
    supervisorCode: 'SUP-017',
    supervisorName: 'Deepa Rao',
    cashAmount: 7400,
    couponAmount: 1600,
    ccAmount: 11200,
    total: 20200,
    status: 'acknowledged',
  },
];

export const SUMMARY_REPORT_DATA: SummaryReportRow[] = [
  {
    id: 'sum-001',
    agentCode: 'AGT-042',
    agentName: 'Rajan Kumar',
    routeCode: 'RT-04',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    parlorCount: 4,
    totalCash: 36200,
    totalCoupon: 8300,
    totalCC: 64600,
    grandTotal: 109100,
    acknowledgedCount: 3,
    pendingCount: 1,
  },
  {
    id: 'sum-002',
    agentCode: 'AGT-038',
    agentName: 'Priya Nair',
    routeCode: 'RT-04',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    parlorCount: 3,
    totalCash: 40600,
    totalCoupon: 10800,
    totalCC: 62400,
    grandTotal: 113800,
    acknowledgedCount: 2,
    pendingCount: 1,
  },
  {
    id: 'sum-003',
    agentCode: 'AGT-051',
    agentName: 'Suresh Babu',
    routeCode: 'RT-05',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    parlorCount: 3,
    totalCash: 14000,
    totalCoupon: 1600,
    totalCC: 23300,
    grandTotal: 38900,
    acknowledgedCount: 2,
    pendingCount: 1,
  },
  {
    id: 'sum-004',
    agentCode: 'AGT-029',
    agentName: 'Anita Desai',
    routeCode: 'RT-04',
    supervisorCode: 'SUP-012',
    supervisorName: 'Meena Sharma',
    parlorCount: 2,
    totalCash: 22100,
    totalCoupon: 5900,
    totalCC: 41200,
    grandTotal: 69200,
    acknowledgedCount: 1,
    pendingCount: 1,
  },
  {
    id: 'sum-005',
    agentCode: 'AGT-063',
    agentName: 'Vikram Singh',
    routeCode: 'RT-06',
    supervisorCode: 'SUP-017',
    supervisorName: 'Deepa Rao',
    parlorCount: 5,
    totalCash: 28400,
    totalCoupon: 6200,
    totalCC: 42800,
    grandTotal: 77400,
    acknowledgedCount: 5,
    pendingCount: 0,
  },
  {
    id: 'sum-006',
    agentCode: 'AGT-071',
    agentName: 'Kavitha Menon',
    routeCode: 'RT-07',
    supervisorCode: 'SUP-017',
    supervisorName: 'Deepa Rao',
    parlorCount: 4,
    totalCash: 21600,
    totalCoupon: 4800,
    totalCC: 33700,
    grandTotal: 60100,
    acknowledgedCount: 4,
    pendingCount: 0,
  },
];

export const COLLECTORS = [
  { code: 'AGT-042', name: 'Rajan Kumar' },
  { code: 'AGT-038', name: 'Priya Nair' },
  { code: 'AGT-051', name: 'Suresh Babu' },
  { code: 'AGT-029', name: 'Anita Desai' },
  { code: 'AGT-063', name: 'Vikram Singh' },
  { code: 'AGT-071', name: 'Kavitha Menon' },
];

export const PARLORS_FILTER = [
  { code: 'PRL-001', name: 'Nexus Mall — Koramangala' },
  { code: 'PRL-007', name: 'Forum Value Mall' },
  { code: 'PRL-019', name: 'Jayanagar 4th Block' },
  { code: 'PRL-031', name: 'Whitefield ITPL Gate' },
  { code: 'PRL-044', name: 'Koramangala 5th Block Kiosk' },
  { code: 'PRL-057', name: 'Marathahalli Bridge' },
  { code: 'PRL-062', name: 'Electronic City Phase 1' },
  { code: 'PRL-068', name: 'MG Road Premium' },
  { code: 'PRL-074', name: 'Sarjapur Road Outlet' },
  { code: 'PRL-083', name: 'Bannerghatta Road Mall' },
  { code: 'PRL-089', name: 'Hebbal Lake View' },
];